### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/high-seas-bias-vote#1]
# Meta

- [ ] Github repo has no description [enable here](https://github.com/NeonGamerBot-QK/high-seas-bias-vote)

- [ ] There is no homepage! [enable here](https://github.com/NeonGamerBot-QK/high-seas-bias-vote)

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT** [here](https://github.com/NeonGamerBot-QK/high-seas-bias-vote/settings)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] This repo has no readme... thats required in lots of repo's **WRITE A README**

- [ ] if possible make your app docker compatible? (beta)

- [ ] if possible make your app docker compatible? (beta)

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**
